### ISSUE TITLE
Getting 'com.android.volley.TimeoutError' volley error.

### ISSUE THREAD

**Issue by ram-readwhere** [faruktoptas/volley-public-key-pinning#1]

**Comment by faruktoptas** [comment]
Are you sure you set the public key correctly?

**Comment by ram-readwhere** [comment]
How can I get "public key". I have tried,
            
          
            
PublicKey key = null;
            SSLSocketFactory factory = HttpsURLConnection.getDefaultSSLSocketFactory();
            SSLSocket socket = null;
            try {
                socket = (SSLSocket) factory.createSocket(HOST, 443);
                socket.startHandshake();
                Certificate[] certs = socket.getSession().getPeerCertificates();
                Certificate cert = certs[0];
                key = cert.getPublicKey();
            } catch (IOException e) {
                e.printStackTrace();
            }
```


It is giving java.net.UnknownHostException: Unable to resolve host : No address associated with hostname

**Comment by faruktoptas** [comment]
Put a breakpoint to line 42 in PubKeyManager.java file then start debugging. The value of “encoded” String is what you need.

Please read this post for details:
https://medium.com/android-bits/android-security-tip-public-key-pinning-with-volley-library-fb85bf761857

**Comment by thasneemp** [comment]
getting SSL Handshake exception in pre Lolipop

**Comment by faruktoptas** [comment]
@thasneemp 
It can be TLS problem. Because TLS v1.1 and v1.2 is [supported but not enabled by default](https://developer.android.com/reference/javax/net/ssl/SSLSocket). You need to enable. Please check this so thread https://stackoverflow.com/questions/28943660/how-to-enable-tls-1-2-support-in-an-android-application-running-on-android-4-1

**Comment by faruktoptas** [comment]
TLS v1.1/v1.2 support added for pre-lollipop devices.
